### ISSUE TITLE
GaussianBlur is already registered in pipeline

### ISSUE THREAD

**Issue by jancylee** [WXinlong/DenseCL#1]
How can I  evalute the performance of the model pretrained in coco(800)?

**Comment by WXinlong** [comment]
@jancylee  For evaluating on downstream detection and segmentation, please refer to [benchmarks/detection/README.md](https://github.com/WXinlong/DenseCL/blob/main/benchmarks/detection/README.md). For evaluating on classification of VOC07 Linear SVM, please refer to [here](https://github.com/WXinlong/DenseCL/blob/main/docs/GETTING_STARTED.md#voc07-linear-svm--low-shot-linear-svm).

**Comment by jancylee** [comment]
When I run your instruction code "./tools/dist_train.sh configs/selfsup/densecl/densecl_coco_800ep.py 8", the code in the line 149 (def forward_train(self, img, **kwargs):)  of **/openselfsup/models/densecl.py**, which used to compute the contrastive loss, is not run. Becasue I try to print the shape of the variate from **line 150 to line 158**, they are not printed.

**Comment by jancylee** [comment]
And Maybe I don't know well about the onpeselfsup, I run your nstruction code "./tools/dist_train.sh configs/selfsup/densecl/densecl_coco_800ep.py 8" with 8 gpus, it only takes 1 hour to finish 800 epochs...

**Comment by trungpx** [comment]
Hello, 

Is there anyone who successfully ran the code from their repo?

I tried installing (remove/reinstall) several times but when run training it kept saying: **KeyError: 'GaussianBlur is already registered in pipeline'**, and the code instantly stopped.

when I run this command: **bash tools/dist_train.sh configs/selfsup/densecl/densecl_coco_800ep.py 8**

I am using torch version 1.7.1, CUDA 9.2. torch.cuda.is_available() = True
