### ISSUE TITLE
2.3 negative sample

### ISSUE THREAD

**Issue by wjczf123** [WXinlong/DenseCL#10]
I have 1 question and hope to hear from you:
In section, 2.3 ''Each negative key t_ is the pooled feature vector of a view from a different image.''
Why not use the other parts of the two views of the same image as negative samples? 
This seems more make sense.

**Comment by WXinlong** [comment]
Please refer to Section 3.3 of the paper for details, i.e., the paragraph 

> Negative samples.

.
https://arxiv.org/pdf/2011.09157.pdf

**Comment by wjczf123** [comment]
Thank you for your reply.
I saw this part.
Have you tried using the other parts of the two views of the same image as negative samples?
This seems more 'hard negative' than sample from a different image.

**Comment by WXinlong** [comment]
We didn't try that.

**Comment by wjczf123** [comment]
OK. Thank you very much.

**Comment by Holmes-GU** [comment]
> I have 1 question and hope to hear from you:
> In section, 2.3 ''Each negative key t_ is the pooled feature vector of a view from a different image.''
> Why not use the other parts of the two views of the same image as negative samples?
> This seems more make sense.

So the 'pooled feature vector of a view from a different image' means the global average pooled vector of a view from a different image? If so, t_ is equal to the global view of a different image?
