### ISSUE TITLE
Question in equation (1) and (2)

### ISSUE THREAD

**Issue by tghong** [WXinlong/DenseCL#12]
Thanks for the great work!

I have a question in equation (1) and (2) in the paper.
In the denominators of these equations, why the temperature hyper-parameter \tau is not used in the "exp(q·k_+)" and "exp(r^s·t^s_+)"?
In https://github.com/WXinlong/DenseCL/blob/main/openselfsup/models/heads/contrastive_head.py#L34, it seems that \tau is applied to all key features.

**Comment by WXinlong** [comment]
Hi, thanks for pointing it out! 
It's a typo and we will correct it in our next version.

**Comment by tghong** [comment]
OK. Thank you!
