### ISSUE TITLE
Details about loss_lambda warmup

### ISSUE THREAD

**Issue by alohays** [WXinlong/DenseCL#16]
Thank you for your great work.
Could you give the implementation detail or code of the loss_lambda warmup setting stated in the DenseCL paper?

**Comment by WXinlong** [comment]
Hi, it is implemented as a hook. I have uploaded it to this repo. Please refer to [hooks/densecl_warmup_hook.py](https://github.com/WXinlong/DenseCL/blob/main/openselfsup/hooks/densecl_warmup_hook.py) for details.

For usage, you just need to add this to your config file:
`
custom_hooks = [ 
    dict(type='DenseCLWarmupHook', start_iters=10000)
]
`
