### ISSUE TITLE
Evaluation setting on Semantic segmentation

### ISSUE THREAD

**Issue by wcy1122** [WXinlong/DenseCL#18]
Thanks for your outstanding work. Here is a question about the evaluation setting on Semantic segmentation
Dis you used "two extra 3×3 convolutions of 256 channels, with BN and ReLU, and then a 1×1 convolution for perpixel classification. The total stride is 16 (FCN-16s [43]). We set dilation = 6 in the two extra 3×3 convolutions, following the large field-of-view design in [6]" this setting during the evaluation of Semantic segmentation (the same as mMoCo), or just used a classic FCN?

**Comment by zzzzzz0407** [comment]
@wcy1122 please check it here. https://github.com/WXinlong/mmsegmentation/blob/master/configs/densecl/fcn_r50-d8.py

**Comment by lcysonya** [comment]
@wcy1122 Did you get the reported results on VOC semantic segmentation？
