### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by hzhupku** [WXinlong/DenseCL#2]
Could you provide me with the training log. My training process is extremely slow. Thank you.

**Comment by WXinlong** [comment]
@hzhupku   Your machine might have a slow data loading issue, you are suggested to convert ImageNet to lmdb format through [folder2lmdb_imagenet.py](https://github.com/WXinlong/DenseCL/blob/main/tools/folder2lmdb_imagenet.py), and use[ this config](https://github.com/WXinlong/DenseCL/blob/main/configs/selfsup/densecl/densecl_imagenet_lmdb_200ep.py) for training.

For COCO dataset, I didn't encounter this issue. But for convenience, the scripts for converting COCO dataset to lmdb format will be uploaded soon.

**Comment by WXinlong** [comment]
@hzhupku  FYI, the [scripts](https://github.com/WXinlong/DenseCL/blob/main/tools/folder2lmdb_coco.py) for converting COCO dataset to lmdb format have been added.
