### ISSUE TITLE
Inferior performance on PASCAL VOC12 with DeepLabV3+

### ISSUE THREAD

**Issue by syorami** [WXinlong/DenseCL#3]
Thanks for revealing your code and the results are impressive. 

I've tried the downloaded DenseCL pretrained models and tested on the VOC semantic segmentation dataset. When using the same FCN architecture, the result performance matches the expectation. The DenseCL ImageNet pretrained model outperforms the ImageNet classification model. However, when replacing the backbones of DeepLabV3+, the DenseCL model showed inferior performance. The results comparisons are as below:

| Arch 	| Dataset 	| Pretrained Model 	|  mIoU 	|
|:----:	|:-------:	|:----------------:	|:-----:	|
| dv3+ 	|  VOC12  	|   Sup ImageNet   	| 71.33 	|
| dv3+ 	|  VOC12  	|   DenseCL COCO   	| 67.51 	|
| dv3+ 	|  VOC12  	| DenseCL ImageNet 	|  69.5 	|

The configs are borrowed from the official configs of MMSEG and I carefully tried to not make much modifications. Wondering if you have ever noticed same behavior on any other models or datasets?

**Comment by WXinlong** [comment]
@syorami  What's your config?  There should be a mismatch in the config.  Please make sure you use the same ResNet architecture as in our provided [config](https://github.com/WXinlong/mmsegmentation/blob/32b0affd560904d275f5b11bb3bacad62450948c/configs/densecl/fcn_r50-d8.py#L7).

**Comment by syorami** [comment]
Yes. I've noticed the difference of backbones between your implementation and MMSEG's so I merged the `ResNetNormal` into the registry. There're are no errors with loading the pretrained model. My complete config is attached: [config.zip](https://github.com/WXinlong/DenseCL/files/6124288/config.zip)

The dataset and schedule configs are as the same as the configs provided by MMSEG except the training iterations, as I found that 3k iterations were already enough to train a VOC12 baseline. The experiments were conducted on 8 V100 GPUs and took around 1.5h. I trained MMSEG's dv3+ without modifications on PASCAL VOC12 previously and got a result of around 72.5 mIoU. So I think 71.33 mIoU is a fairly close result here when considering the backbone difference. 

It would be appreciated that if you could help check the config or give some advice.

**Comment by WXinlong** [comment]
Can you post the results of MoCov2 model, which can be downloaded from [openselfsup](https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/MODEL_ZOO.md)?
And also the DeepLabV3+ training logs of these three pre-trained models.
I will try to help.

**Comment by syorami** [comment]
I didn't conduct experiments of MoCov2 but I will give a try.

**Comment by WXinlong** [comment]
I'm closing this issue for no requested information.
