### ISSUE TITLE
The performance of DenseCL on classification task

### ISSUE THREAD

**Issue by ChongjianGE** [WXinlong/DenseCL#5]
Hi, @WXinlong . Thanks for the great work.
Since the article claims that the proposed method mainly aims to solve the dense prediction tasks (e.g., detection and segmentation), I wonder if you have tried DenseCL on the classification task and what is the performance.

**Comment by WXinlong** [comment]
@ChongjianGE  Thanks for the interest.  We tried the classification on VOC dataset and the results are reported in the paper. Overall, there is no clear gain on the classification task.
