### ISSUE TITLE
The performance of detection in COCO

### ISSUE THREAD

**Issue by Peipeilvcm** [WXinlong/DenseCL#7]
Based on MMDetection，train COCO2017 & val COCO2017

FasterR-CNN,r50 From **torchvision://resnet50**

           1x: bbox_mAP: 0.3750

FasterR-CNN,r50 From **My Reproduction Model Pretrained on ImageNet**

           1x: bbox_mAP: 0.3580

FasterR-CNN,r50 From **Your Pretrained Mode on ImageNetl**

           1x: bbox_mAP: 0.3550

Which is not as good as expected? Could you give a help？

**Comment by WXinlong** [comment]
Did you use SyncBN for each component during the detector training? If not, you should do so.
Please see this [config](https://github.com/WXinlong/DenseCL/blob/main/benchmarks/detection/configs/R_50_FPN_1x.yaml) for reference.
The reason can be found in MoCo paper.

**Comment by Peipeilvcm** [comment]
> Did you use SyncBN for each component during the detector training? If not, you should do so.
> Please see this [config](https://github.com/WXinlong/DenseCL/blob/main/benchmarks/detection/configs/R_50_FPN_1x.yaml) for reference.
> The reason can be found in MoCo paper.

Thanks for your quick reply, I will try it, and updates the results

**Comment by Peipeilvcm** [comment]
Based on MMDetection，train COCO2017 & val COCO2017, No freeze stage,Add SyncBN

FasterR-CNN,r50 From **torchvision://resnet50**

           1x: bbox_mAP: 0.3740

FasterR-CNN,r50 From **My Reproduction Model Pretrained on ImageNet**

           1x: bbox_mAP: 0.3780

FasterR-CNN,r50 From **Your Pretrained Mode on ImageNetl**

           1x: bbox_mAP: 0.3750
