### ISSUE TITLE
KeyError: 'GaussianBlur is already registered in pipeline'

### ISSUE THREAD

**Issue by trungpx** [WXinlong/DenseCL#8]
Hi,
I am trying to run the code to train COCO (train2017) self supervised, I tried installing several times with the instructions but when run training it kept saying a lot of messages: **KeyError: 'GaussianBlur is already registered in pipeline'**, and the code instantly stopped.

Command: **bash tools/dist_train.sh configs/selfsup/densecl/densecl_coco_800ep.py 8**

I am using torch version 1.7.1, CUDA 9.2. torch.cuda.is_available() = True

Have you tried reproduced the results in an entire new machine and faced this error? 

Could you help me some suggestions on this bug?

**Comment by WXinlong** [comment]
It is now fixed. Can you try again?  It is because your torch version is higher than ours.

**Comment by trungpx** [comment]
Thanks for your nice feedback. It works now. 

I'm not aware of that the torch version is the issue. Since the installation INSTALL.MD said it requires: "Python 3.5+, PyTorch 1.1 or higher, CUDA 9.0 or higher". 

Although it is working with torch 1.7.1 now, it shows that some packages is deprecated. Maybe the results between different versions of torch gives the slight change on the results. I am going to downgrade and test with a lower version of torch.

**Comment by 4-0-4-notfound** [comment]
> It is now fixed. Can you try again? It is because your torch version is higher than ours.

Hi, would you like to list your experiment environment? Which version of  python, pytorch, and cuda did you use?
